apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gcloud-instance-telegram-bot.fullname" . }}-telegram
  labels:
    app: {{ template "gcloud-instance-telegram-bot.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  token:  {{ .Values.telegram.token | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gcloud-instance-telegram-bot.fullname" . }}-gcloud-key
  labels:
    app: {{ template "gcloud-instance-telegram-bot.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  google: {{ .Values.gce.serviceAccount.key | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gcloud-instance-telegram-bot.fullname" . }}-app-auth
  labels:
    app: {{ template "gcloud-instance-telegram-bot.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  password: {{ .Values.app.password | b64enc | quote }}
